// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using kuvuBot.Data;
//
//    var legacyStat = LegacyStat.FromJson(jsonString);

namespace kuvuBot.Data
{
    using Newtonsoft.Json;

    public partial class LegacyStat
    {
        [JsonProperty("guilds")]
        public long Guilds { get; set; }

        [JsonProperty("channels")]
        public long Channels { get; set; }

        [JsonProperty("users")]
        public long Users { get; set; }
    }
}
